### ISSUE TITLE
Feature Request: Option to set font size for Headers, Facet

### ISSUE THREAD

**Issue by SamRockX** [Microsoft/PowerBI-visuals-FacetKey#30]
Feature Request #1: 
Option to set font size for Headers, Facet. At full screen, the Facet fonts look really big somethings and this this limits the number of values shown too.

Would be great if we could control the fonts for "Count" and Range too (but not necessary). It could be same as Facet font size.

(Submitting feature requesting as requested by @jryu01 )

**Comment by jryu01** [comment]
Closing as there's no current plan for additional features.
