### ISSUE TITLE
Feature Request: Show Range and Segment values in Tooltip

### ISSUE THREAD

**Issue by SamRockX** [Microsoft/PowerBI-visuals-FacetKey#31]
Feature Request #2:
The "Range Value" feature is the best thing I have seen in a BI tool! Right now, its just shows a blue bar of different ranges. Could we have an option where, when the mouse is hovered over a binned range, it shows us the underlying Values too in a Tool Tip format?

Same could work for Segmented data as well. 

Also, on the "Count" property, a Tooltip could show Column name of what is being Counted (or summed). After a while we tend to forget or even new users would not know what the count is for. A tooltip on mouse hover can show them the info.

**Comment by jryu01** [comment]
Closing as there's no current plan for additional features.
