### ISSUE TITLE
Feature Request: Alternate way to set Icon Class

### ISSUE THREAD

**Issue by SamRockX** [Microsoft/PowerBI-visuals-FacetKey#33]
Feature Request:
Use of Font Awesome icon is a GREAT feature! 
However right now it always depends on a Column to populate its icon. Can there be a way where I enter a FA icon name directly into the property window? This would eliminate the necessity to have a special column designated only for this purpose.

(More explanation from my comments)

> its not really a high priority request, but I will tell you from where I am coming. I am primarily using the FacetKey visual as Slicer, due to the fact that it allows me to Search, Select, segment, filter, and even have metrics (like count, sum of another field!!) These are amazing features to have in a Slicer. It changes the way my user filter their data. The icon feature I requested could be similar to assigning a "Background color" or Font size. Alternate to assigning a Column (with FA icon name), if I could also specify my own text, it would remove the need to create a "icon" column only for this purpose.

**Comment by jryu01** [comment]
Closing as there's no current plan for additional features.
