### ISSUE TITLE
Feature Request: Option to hide Search box

### ISSUE THREAD

**Issue by SamRockX** [Microsoft/PowerBI-visuals-FacetKey#34]
Feature Request:
Finally, could we have an option to hide the Search Box? Sometime I have less than 5 items in the FacetKey, in such case we would not need a Search box :)

This also makes space for more Range

(While you are at it, may be allow us to hide borders as well :) 
It looks great, but often I am forced to align my other visuals with it to make it look consistent :D  )

**Comment by jryu01** [comment]
Closing as there's no current plan for additional features.
