### ISSUE TITLE
Feature Request: Scrollbars on Facetkeys only

### ISSUE THREAD

**Issue by SamRockX** [Microsoft/PowerBI-visuals-FacetKey#35]
We have Range Values added on top of the FacetKeys. Now when I click the "more" option for a FacetKey, it just expands the Visual to the end of the screen (even if there is another visual below). Then the whole visual gets a scrollbar. 

If somehow, the scrollbar could be limited to the respective Facet only, then it would have other filters fixed at the set height.

**Comment by jryu01** [comment]
Closing as there's no current plan for additional features.
