### ISSUE TITLE
Facet Key doesn't work on PowerBI online

### ISSUE THREAD

**Issue by MsSQLGirl** [Microsoft/PowerBI-visuals-FacetKey#45]
It looks like Facet Key works when used for developing locally on Power BI Desktop. As soon as it gets published online, it seems to stop working. 
Power BI Desktop - no filter selected
![image](https://user-images.githubusercontent.com/6405919/31853625-6ca3c2ac-b640-11e7-8a86-7ecf63829ff0.png)

Power BI Desktop - filter selected (works!)
![image](https://user-images.githubusercontent.com/6405919/31853615-57478704-b640-11e7-9ae6-9780da5c9cef.png)

Power BI online - no filter selected
![image](https://user-images.githubusercontent.com/6405919/31853633-805eb3ba-b640-11e7-8d9c-2fb671a97cf4.png)

Power BI online - filter selected (doesn't work)
![image](https://user-images.githubusercontent.com/6405919/31853637-90b202d0-b640-11e7-82f2-a3136c81aa1a.png)

This seems to be a regression from an older version.

**Comment by jryu01** [comment]
Selection is broken as pbi dropped support for legacy api in the latest update that we've been using. We are investigating the issue right now.

**Comment by psmacmur** [comment]
PowerBI fixed the issue internally
